server:
  port: 8080

spring:
  application:
    name: book-store-api-gateway
  cloud:
    gateway:
      routes:
        - id: book-service
          uri: lb://BOOK-SERVICE  # Changed to match the registered name
          predicates:
            - Path=/books/**
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/orders/**
        - id: inventory-service
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/inventory/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true